"use client";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import type { SiteContent } from "../lib/site-content";
type Data = { counts: { volunteers: number; partners: number; mentors: number; funders: number }; availability: { slot: string; count: number }[]; records: { id: string; name: string; email: string; type: string; submittedAt: string; availability?: string }[] };
type Media = { id?: string; name: string; url: string; size: number };
const fields: { key: keyof SiteContent; label: string; long?: boolean }[] = [{ key: "heroImage", label: "Hero image URL" }, { key: "heroTitle", label: "Hero headline", long: true }, { key: "heroIntro", label: "Hero introduction", long: true }, { key: "visionTitle", label: "Vision heading", long: true }, { key: "visionCopy", label: "Vision text", long: true }, { key: "ctaTitle", label: "Call-to-action heading", long: true }, { key: "ctaCopy", label: "Call-to-action text", long: true }];
export default function AdminDashboard() {
  const [content, setContent] = useState<SiteContent | null>(null); const [data, setData] = useState<Data | null>(null); const [media, setMedia] = useState<Media[]>([]); const [status, setStatus] = useState(""); const [uploading, setUploading] = useState(false);
  function refresh() { fetch("/api/dashboard").then(r => r.json()).then(setData); fetch("/api/media").then(r => r.json()).then(setMedia); }
  useEffect(() => { fetch("/api/site-content").then(r => r.json()).then(setContent); refresh(); }, []);
  function update(key: keyof SiteContent, value: string) { if (content) setContent({ ...content, [key]: value }); }
  async function save(e: FormEvent) { e.preventDefault(); if (!content) return; setStatus("Saving…"); const r = await fetch("/api/site-content", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(content) }); setStatus(r.ok ? "Published." : "Could not save content."); }
  async function upload(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; setUploading(true); const form = new FormData(); form.append("file", file); const r = await fetch("/api/media", { method: "POST", body: form }); const uploaded = await r.json(); setUploading(false); if (!r.ok) return setStatus(uploaded.error); setMedia(list => [uploaded, ...list]); if (content) setContent({ ...content, heroImage: uploaded.url }); setStatus("Image uploaded. Click Save and publish to use it as the hero image."); e.target.value = ""; }
  if (!content || !data) return <main className="admin-shell"><p>Loading dashboard…</p></main>;
  const cards = [["Volunteers", data.counts.volunteers], ["Partners", data.counts.partners], ["Mentors", data.counts.mentors], ["Funders", data.counts.funders]];
  return <main className="admin-shell"><header><div><p className="eyebrow">Dignity to Rise</p><h1>Operations dashboard</h1><p>Track participation, manage your image library, and update the essential homepage content.</p></div><div className="admin-actions"><a href="/api/export">Export CSV ↓</a><a href="/" target="_blank">View website ↗</a></div></header>
    <section className="stats-grid">{cards.map(([label, count]) => <article key={label as string}><span>{label}</span><strong>{count as number}</strong><small>Submitted forms</small></article>)}</section>
    <section className="tracking-grid"><article className="tracking-card"><div className="section-title"><div><p className="eyebrow">Volunteer planning</p><h2>Availability</h2></div><button className="refresh-button" onClick={refresh}>Refresh</button></div>{data.availability.length ? <div className="availability-list">{data.availability.map(i => <div key={i.slot}><span>{i.slot}</span><b>{i.count}</b></div>)}</div> : <p className="empty-copy">Availability appears after volunteers submit the form.</p>}</article><article className="tracking-card"><p className="eyebrow">Image library</p><h2>Images</h2><label className="upload-control">{uploading ? "Uploading…" : "Import image"}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} disabled={uploading} /></label><p className="empty-copy">JPG, PNG, or WebP — maximum 8 MB.</p><div className="media-list">{media.map(image => <button type="button" key={image.url} onClick={() => { update("heroImage", image.url); setStatus(`${image.name} selected as hero image. Click Save and publish.`); }}><img src={image.url} alt="" /><span>{image.name}</span><small>{Math.ceil(image.size / 1024)} KB</small></button>)}</div></article></section>
    <section className="records-card"><div className="section-title"><div><p className="eyebrow">People tracker</p><h2>Recent activity</h2></div><a className="refresh-button" href="/api/export">Export all CSV ↓</a></div>{data.records.length ? <div className="record-table">{data.records.map(r => <article key={r.id}><div><b>{r.name}</b><span>{r.email}</span>{r.availability && <small>{r.availability}</small>}</div><div><em>{r.type}</em><time>{r.submittedAt ? new Date(r.submittedAt).toLocaleDateString() : "New"}</time></div></article>)}</div> : <p className="empty-copy">Submissions will appear here automatically.</p>}</section>
    <form className="content-form" onSubmit={save}><div className="form-section-heading"><p className="eyebrow">Essential website editor</p><h2>Homepage content</h2><p>Only key visitor-facing content is editable here.</p></div>{fields.map(({ key, label, long }) => <label key={key}>{label}{long ? <textarea value={content[key] as string} onChange={e => update(key, e.target.value)} /> : <input value={content[key] as string} onChange={e => update(key, e.target.value)} />}</label>)}<div className="impact-editor"><p className="eyebrow">Movement in numbers</p><input aria-label="Impact section heading" value={content.impactHeading} onChange={e => setContent({ ...content, impactHeading: e.target.value })} />{content.impactStats.map((stat, index) => <div key={index}><input aria-label="Stat value" value={stat.value} onChange={e => { const impactStats = [...content.impactStats]; impactStats[index] = { ...stat, value: e.target.value }; setContent({ ...content, impactStats }); }} /><input aria-label="Stat label" value={stat.label} onChange={e => { const impactStats = [...content.impactStats]; impactStats[index] = { ...stat, label: e.target.value }; setContent({ ...content, impactStats }); }} /></div>)}</div><div className="content-submit"><button>Save and publish</button><span>{status}</span></div></form></main>;
}
