"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import type { SiteContent } from "../lib/site-content";

type Data = { counts: { volunteers: number; partners: number; mentors: number; funders: number }; availability: { slot: string; count: number }[]; records: { id: string; name: string; email: string; type: string; submittedAt: string; availability?: string }[] };
type Media = { id?: string; name: string; url: string; size: number };
const exportCollections = ["volunteers", "partners", "mentors", "funders"] as const;
const exportLabel: Record<(typeof exportCollections)[number], string> = { volunteers: "Volunteers", partners: "Partners", mentors: "Mentors", funders: "Funders" };
const fields: { key: keyof SiteContent; label: string; long?: boolean }[] = [
  { key: "heroImage", label: "Hero image URL" }, { key: "heroTitle", label: "Hero headline", long: true }, { key: "heroIntro", label: "Hero introduction", long: true },
  { key: "visionTitle", label: "Vision heading", long: true }, { key: "visionCopy", label: "Vision text", long: true }, { key: "ctaTitle", label: "Call-to-action heading", long: true }, { key: "ctaCopy", label: "Call-to-action text", long: true }
];

export default function AdminDashboard() {
  const [content, setContent] = useState<SiteContent | null>(null);
  const [data, setData] = useState<Data | null>(null);
  const [media, setMedia] = useState<Media[]>([]);
  const [status, setStatus] = useState("");
  const [uploading, setUploading] = useState(false);
  const [activeTab, setActiveTab] = useState("overview");

  function refresh() { fetch("/api/dashboard").then((r) => r.json()).then(setData); fetch("/api/media").then((r) => r.json()).then(setMedia); }
  useEffect(() => { fetch("/api/site-content").then((r) => r.json()).then(setContent); refresh(); }, []);
  function update(key: keyof SiteContent, value: string) { if (content) setContent({ ...content, [key]: value }); }
  function updateSector(index: number, key: "title" | "image", value: string) { if (!content) return; const sectors = [...content.sectors]; sectors[index] = { ...sectors[index], [key]: value }; setContent({ ...content, sectors }); }
  function updateProjects(index: number, key: "liveProjects" | "doneProjects" | "futureProjects", value: string) { if (!content) return; const sectors = [...content.sectors]; const projects = value.split("\n").map((item) => item.trim()).filter(Boolean); sectors[index] = { ...sectors[index], [key]: projects, [key === "liveProjects" ? "live" : key === "doneProjects" ? "done" : "future"]: String(projects.length) }; setContent({ ...content, sectors }); }
  async function save(event: FormEvent) { event.preventDefault(); if (!content) return; setStatus("Saving..."); const response = await fetch("/api/site-content", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(content) }); setStatus(response.ok ? "Published." : "Could not save content."); }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setUploading(true); const form = new FormData(); form.append("file", file); const response = await fetch("/api/media", { method: "POST", body: form }); const uploaded = await response.json(); setUploading(false); if (!response.ok) return setStatus(uploaded.error); setMedia((list) => [uploaded, ...list]); if (content) setContent({ ...content, heroImage: uploaded.url }); setStatus("Image uploaded. Click Save and publish to use it as the hero image."); event.target.value = ""; }

  if (!content || !data) return <main className="admin-shell"><p>Loading dashboard...</p></main>;
  const cards = [["Volunteers", data.counts.volunteers], ["Partners", data.counts.partners], ["Mentors", data.counts.mentors], ["Funders", data.counts.funders]];
  const total = cards.reduce((sum, [, count]) => sum + (count as number), 0);
  const maxCount = Math.max(...cards.map(([, count]) => count as number), 1);
  const recentCount = data.records.filter((record) => record.submittedAt && Date.now() - new Date(record.submittedAt).getTime() <= 7 * 86400000).length;
  const goTo = (tab: string) => { setActiveTab(tab); document.getElementById(tab)?.scrollIntoView({ behavior: "smooth", block: "start" }); };

  return <main className="admin-shell admin-shell-layout">
    <aside className="admin-sidebar"><a className="admin-brand" href="/"><span>DIGNITY</span><b>TO RISE</b></a><p>ADMIN PORTAL</p>{[["overview", "Overview"], ["people", "People & exports"], ["content", "Content editor"], ["media", "Media library"]].map(([id, label]) => <button key={id} className={activeTab === id ? "active" : ""} onClick={() => goTo(id)}>{label}</button>)}<div><a href="/" target="_blank">View public website ↗</a><a href="/api/export/sectors">Sectors CSV ↓</a></div></aside>
    <div className="admin-workspace">
    <header id="overview"><div><p className="eyebrow">Dignity to Rise</p><h1>Operations dashboard</h1><p>Clear, up-to-date visibility of people joining the movement.</p></div><div className="admin-actions"><button onClick={refresh}>Refresh data</button></div></header>
    <section className="stats-grid">{cards.map(([label, count]) => <article key={label as string}><span>{label}</span><strong>{count as number}</strong><small>Submitted forms</small></article>)}</section>
    <section className="tracking-grid"><article className="tracking-card analytics-card"><p className="eyebrow">Participation analytics</p><h2>{total} people in the pipeline</h2><p className="empty-copy">{recentCount} new submission{recentCount === 1 ? "" : "s"} in the last 7 days.</p><div className="distribution">{cards.map(([label, count]) => <div key={label as string}><span>{label}</span><i><b style={{ width: `${((count as number) / maxCount) * 100}%` }} /></i><strong>{count as number}</strong></div>)}</div></article><article className="tracking-card"><div className="section-title"><div><p className="eyebrow">Volunteer planning</p><h2>Availability</h2></div></div>{data.availability.length ? <div className="availability-list">{data.availability.map((item) => <div key={item.slot}><span>{item.slot}</span><b>{item.count}</b></div>)}</div> : <p className="empty-copy">Availability appears after volunteers submit the form.</p>}</article></section>
    <section className="records-card" id="people"><div className="section-title"><div><p className="eyebrow">People tracker</p><h2>Recent activity & separate exports</h2></div><button className="refresh-button" onClick={refresh}>Refresh</button></div><div className="admin-actions" aria-label="Separate collection exports">{exportCollections.map((collection) => <div key={collection}><span>{exportLabel[collection]}</span><a href={`/api/export?collection=${collection}&format=xlsx`}>Excel</a><a href={`/api/export?collection=${collection}&format=pdf`}>PDF</a></div>)}</div>{data.records.length ? <div className="record-table">{data.records.map((record) => <article key={record.id}><div><b>{record.name}</b><span>{record.email}</span>{record.availability && <small>{record.availability}</small>}</div><div><em>{record.type}</em><time>{record.submittedAt ? new Date(record.submittedAt).toLocaleDateString() : "New"}</time></div></article>)}</div> : <p className="empty-copy">Submissions will appear here automatically.</p>}</section>
    <section className="tracking-card media-card" id="media"><p className="eyebrow">Image library</p><h2>Media</h2><label className="upload-control">{uploading ? "Uploading..." : "Import image"}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} disabled={uploading} /></label><p className="empty-copy">JPG, PNG, or WebP - maximum 8 MB.</p><div className="media-list">{media.map((image) => <button type="button" key={image.url} onClick={() => { update("heroImage", image.url); setStatus(`${image.name} selected as hero image. Click Save and publish.`); }}><img src={image.url} alt="" /><span>{image.name}</span><small>{Math.ceil(image.size / 1024)} KB</small></button>)}</div></section>
    <form className="content-form" id="content" onSubmit={save}><div className="form-section-heading"><p className="eyebrow">Essential website editor</p><h2>Homepage content</h2><p>Only key visitor-facing content is editable here.</p></div>{fields.map(({ key, label, long }) => <label key={key}>{label}{long ? <textarea value={content[key] as string} onChange={(event) => update(key, event.target.value)} /> : <input value={content[key] as string} onChange={(event) => update(key, event.target.value)} />}</label>)}
      <div className="impact-editor"><p className="eyebrow">Movement in numbers</p><input aria-label="Impact section heading" value={content.impactHeading} onChange={(event) => setContent({ ...content, impactHeading: event.target.value })} />{content.impactStats.map((stat, index) => <div key={index}><input aria-label="Stat value" value={stat.value} onChange={(event) => { const impactStats = [...content.impactStats]; impactStats[index] = { ...stat, value: event.target.value }; setContent({ ...content, impactStats }); }} /><input aria-label="Stat label" value={stat.label} onChange={(event) => { const impactStats = [...content.impactStats]; impactStats[index] = { ...stat, label: event.target.value }; setContent({ ...content, impactStats }); }} /></div>)}</div>
      <div className="sector-editor"><div><p className="eyebrow">Live opportunities</p><h2>Six sectors</h2><p>Add one project per line. The live, completed, and future totals update automatically on the public cards, which visitors can open to view the projects.</p></div><div className="sector-editor-grid">{content.sectors.map((sector, index) => <article key={index}><label>Sector name<input value={sector.title} onChange={(event) => updateSector(index, "title", event.target.value)} /></label><label>Image path or URL<input value={sector.image} onChange={(event) => updateSector(index, "image", event.target.value)} /></label><div className="sector-counts"><span>{sector.liveProjects.length} live</span><span>{sector.doneProjects.length} done</span><span>{sector.futureProjects.length} future</span></div><label>Live projects<textarea value={sector.liveProjects.join("\n")} onChange={(event) => updateProjects(index, "liveProjects", event.target.value)} /></label><label>Completed projects<textarea value={sector.doneProjects.join("\n")} onChange={(event) => updateProjects(index, "doneProjects", event.target.value)} /></label><label>Future projects<textarea value={sector.futureProjects.join("\n")} onChange={(event) => updateProjects(index, "futureProjects", event.target.value)} /></label></article>)}</div></div>
      <div className="content-submit"><button>Save and publish</button><span>{status}</span></div>
    </form></div>
  </main>;
}
